### ISSUE TITLE
Respond.js issues in IE: w.body is null or not an object error

### ISSUE THREAD

**Issue by JennaPG** [scottjehl/Respond#130]
I'm having trouble getting respond.min.js to work in IE. I'm getting an error that says:

Message: 'w.body' is null or not an object
Line: 6
Char: 1951
Code: 0

Here's the setup:

```
<!DOCTYPE HTML>
<html class="no-js">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<?php echo "<title>".(isset($title)?$title:"TheDefaultTitle")."</title>\n"; ?> 
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="author" content="" >
<link rel="icon" href="/_images/favicon.ico"/>
<!--This is a font-replacement service-->
<link rel="stylesheet" href="http://f.fontdeck.com/abc123<?php echo $_SERVER['SERVER_NAME']; ?>/16000.css" type="text/css" />
<!--This is my stylesheet containing media queries-->
<link rel="stylesheet" href="/css/styles.css" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<script type="text/javascript" src="/js/modernizr.js"></script>
<script type="text/javascript" src="/js/respond.min.js"></script>
<!--This is a responsive image slider plugin-->
<script type="text/javascript" src="/js/jquery.flexslider-min.js"></script>
<!--This contains various site-specific js - stuff like tabs-->
<script type="text/javascript" src="/js/ncff.js"></script>
</head>

<body class="<?php echo "$bodyclass"?>">
```

Then, I have the following php at the top of every page, so that I can dynamically assign a body class and page title:

```
<?php
$title = "titleofthepage";
$bodyclass = "home";
require('includes/header.php');
?>
```

Everything's working beautifully in every other browser I've tested (Firefox - both modern versions and 3.6, Chrome, and Safari, on both macs and PCs). Modernizr kicks in, media queries are working great, etc. However, in IE, (I've been mostly testing 8) I get the error that I listed above, and the media queries are not applied. It loads the base/mobile styles. But, when I start to RESIZE the window, the media queries do seem to kick in. (There are of course a whole bunch of other issues I'll have to troubleshoot in the css, but one thing at a time.) 

One thing that I worry might be affecting things. On the homepage, I have a nice responsive image slider. I did not want to simply hide the `<div>` that contains the slides - because the browser would still be loading large images regardless of whether they were supposed to be visible in the mobile version or not. I didn't want the html containing this section to load at all - therefore optimizing the load time for our mobile users. So, I used the following javascript to detect window size, and insert some html if it was larger than the prescribed width. Here's that code:

```
<script type="text/javascript">
$(function() {
    if ($(window).width() >= 600) {
    $("div.stripe").append("<div class=\"flexslider-container\">\<div class=\"flexslider\"><ul class=\"slides\">\
    <li><div class=\"overlay\"><div class=\"caption\"><h3>It takes <span class=\"red\">training</span><br />to be a hero</h3><a href=\"/donate.php\">Donate Now</a></div></div><img src=\"/_images/hero2.jpg\" /></li>\
    <li><div class=\"overlay\"><div class=\"caption\"><h3>It takes <span class=\"red\">education</span> to be a leader</h3><a href=\"/donate.php\">Donate Now</a></div></div> <img src=\"/_images/hero1.jpg\" /></li>\
    <li><div class=\"overlay\"><div class=\"caption\"><h3>It takes <span class=\"red\">support</span> to serve a community</h3><a href=\"/donate.php\">Donate Now</a></div></div><img src=\"/_images/hero3.jpg\" /></li>\
    </ul></div></div>");};
});

$(document).ready(function() {
    $(".flexslider").flexslider({
      animation: "slide",
      controlsContainer: ".flexslider-container",
      controlNav:false,
      directionNav:false,
      slideshowSpeed: 6000,
      animationDuration: 600
  });
});
</script>
```

I tried removing this code completely, to see if it was the culprit of breaking respond.js. It doesn't appear to be, as the same thing happens in IE whether this is present or not - plus, it's happening not only on the home page, but on interior pages as well, which do not have the flex slider.

I've also tried switching up the order in which files are being loaded in the `<head>` as well as using "if ie" conditionals to load the stylesheet either before respond.js or after it, depending on the browser. When I load the stylesheet AFTER respond.js, the error goes away, but the respond script doesn't work at all - either on page load or when I resize the window.

I've tried removing every `<link>` and `<script>` file in the head, one at a time, to see if I could find a conflict. 

I'm out of ideas. Anyone else encountered this issue or think they might know what's going on? Any help is very much appreciated. 

*Side note - I'm a designer who codes. So, my designs may be pretty, but sometimes my code...not so much. I'm working on that. Constructive criticism is always welcome - I'm eager to learn and improve. Thanks!

**Comment by xesrochers** [comment]
In our scenario, we had our MasterPage with a call to response.js AND an iFrame which called response.js.

So we had 2 calls to response.js on the same page... and got the infamous j.body error.

Once we got rid of the response.js call in the iFrame, all was fine. 

Hope this helps out!

**Comment by jasonruz** [comment]
To fix my 'j.body' error I had to move the `<script>` declaration from the `<head>` to the `<body>`. So, instead of:
```html
  <head>
      <!--[if lt IE 9]>
          <script src="respond.min.js"></script>
      <![endif]-->
  </head>
```
I had to use:
```html
  <body>
      <!--[if lt IE 9]>
          <script src="respond.min.js"></script>
      <![endif]-->
      ... the rest of my body content ...
  </body>
```

**Comment by ekasinggih** [comment]
@jasonruz thanks dude.. it's work for me at ie7
