### ISSUE TITLE
Amazon S3 CORS Support: do we still need the proxy script?

### ISSUE THREAD

**Issue by pilap82** [scottjehl/Respond#152]
Hi,
does the recent announcement of Amazon of CORS (Cross Origin Resource Sharing) support for S3 will allow us to no longer use the proxy script? (if respond.min.js is hosted on S3)

Thanks for your insight.

p.

Announcement: http://aws.amazon.com/about-aws/whats-new/2012/08/31/amazon-s3-announces-cross-origin-resource-sharing-CORS-support/

**Comment by hanmomhanda** [comment]
I'm using respond.js and bootstrap.css together to properly show HTML5 stuffs in IE8.
My respond.js in amazon S3 works well if only I enable the CORS in the S3 console, even without any respond proxy things.
But bootstrap.css must be in the same domain. If I use bootstrap.css from S3, the UI breaks down.
I don't know the exact reason but I could fix my problem.
