### ISSUE TITLE
@Media Queries not working in lte IE8 due to spaces in breakpoint dimension parentheses

### ISSUE THREAD

**Issue by jonrandahl** [scottjehl/Respond#179]
Just wanted to let everyone know of an issue I ran into in Respond.js v1.1.0 with IE9 set to IE8 or 7 view, as well as on a native IE8 install. 
I had a media query set as such:
"@media only screen and ( max-width: 1280px ) {...}" <- note the spaces inside the dimension call which was then causing the browser to not render this, or any other following, adjusted viewport styles.
After a whole load of googling to no avail I went back in to see what was different in this media query to the single media query above it which was applying:
"@media only screen and (min-width:1280px) {...}" <- note: no spaces in this one, or any others after the offending one noted for that matter!
I then removed the spaces, and tested this in IE8 and 7, and both are now displaying the correct styles for the required dimensions!
Note, it's only the initial space that throws IE out, the trailing one doesn't seem to affect anything in case you're wondering.

Just thought I would share this "head-meet-desk" moment and the "warm-fuzzies" revelation that followed!

Thank you for your time and patience,
Jon

**Comment by Erickmok** [comment]
thanks a lot !! this help me so much, sorry but fucking ie 8 !!

**Comment by jigar140291** [comment]
respond.js supports on page media query under <style> tag ?
