### ISSUE TITLE
the cross-domain example http://scottjehl.github.io/Respond/cross-domain/example.html it doesn't work in ie8!

### ISSUE THREAD

**Issue by PanJiaChen** [scottjehl/Respond#318]

**Comment by bjornicus** [comment]
Also ran into this today. After some debugging we discovered it was because 
https://rawgithub.com/scottjehl/Respond/master/test/test.css
now redirects to 
https://rawgit.com/scottjehl/Respond/master/test/test.css

so if you replace all 'rawgithub' with 'rawgit' in the file it will work fine.

**Comment by fritx** [comment]
@bjornicus why not provide a PR ;) just kidding
