### ISSUE TITLE
Only works with separate CSS file - IE8

### ISSUE THREAD

**Issue by entozoon** [scottjehl/Respond#329]
Another issue for proper IE8 I'm afraid (running on actual XP, Document mode: IE8 Standards).

It works fine when the CSS is in it's own file, such as in this example I whipped up:
http://yays.co/keep/respond-test-ie8-separate.html

However, when the styles are actually in the markup of the page.. it doesn't work in IE8, as you can see in this example:
http://yays.co/keep/respond-test-ie8.html

**Comment by OllyHodgson** [comment]
This is a known issue, mentioned in [the Support & Caveats section of the readme](https://github.com/scottjehl/Respond/blob/master/README.md#support--caveats):

> Respond.js doesn't parse CSS referenced via @import, *nor does it work with media queries within style elements*, as those styles can't be re-requested for parsing.

**Comment by entozoon** [comment]
Cool, might be worth adding in what browsers this affects, as it seems to be fine on Chrome and Firefox :)

**Comment by OllyHodgson** [comment]
> it seems to be fine on Chrome and Firefox 

They support media queries natively - they don't need respond.js to help out :)

**Comment by entozoon** [comment]
Touché
