### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by hiebj** [scottjehl/Respond#330]
Do you have any plans to publish/maintain this as an NPM package? I have been using NPM to pull this in as a dependency, but I can only point to the github repo. It would be nice to pull down an official package from the npmjs repository.

**Comment by nilssolanki** [comment]
I completely agree. A lot of people (myself included) are using a workflow with grunt, gulp etc, and they tend to install the packages via npm.

**Comment by jefflembeck** [comment]
Somebody put this up on NPM for us a bit back. We might have to reclaim it, but the project has really slowed down maintenance-wise (to say the least) - https://www.npmjs.com/package/respond.js
